import test from 'node:test';
import assert from 'node:assert/strict';
import {GameModel,newGame,validateSave} from '../dist/model.js';
import {QUESTS,BUSINESSES,LOCATIONS,WORK} from '../dist/data.js';

function completeJob(m){
 const j=m.s.job;if(!j)return;m.s.inside=false;m.s.riding=false;
 if(j.type==='courier'){const p=LOCATIONS.find(l=>l.id===j.target);m.s.position={x:p.x,z:p.z};assert.ok(m.work('deliver'))}
 else if(j.type==='cleaning')while(m.s.job){const i=m.s.job.progress,[x,z]=WORK.cleaning[i];m.s.position={x,z};assert.ok(m.work('trash',i))}
 else while(m.s.job){const i=m.s.job.progress;m.s.position={...WORK.crate};assert.ok(m.work('crate'));m.s.position={...WORK.shelves[i]};assert.ok(m.work('shelf',i))}
}

test('new games start at 08:00 in story and sandbox',()=>{assert.equal(newGame().minute,480);assert.equal(newGame(true).minute,480)});
test('new story starts penniless and collects each bottle once',()=>{let m=new GameModel();assert.equal(m.s.money,0);assert.equal(m.collect(0),true);assert.equal(m.collect(0),false);assert.equal(m.count('bottle'),1);for(let i=1;i<5;i++)m.collect(i);assert.equal(m.s.quest,1);assert.equal(m.s.money,500);m.recycle();assert.equal(m.count('bottle'),0);assert.equal(m.s.money,1425);assert.equal(m.s.quest,2)});
test('stacking is atomic for both weight and slots',()=>{let m=new GameModel();assert.ok(m.add('bottle',40));assert.equal(m.s.inventory.length,2);assert.equal(m.weight,4);const before=JSON.stringify(m.s.inventory);assert.equal(m.add('water',40),false);assert.equal(JSON.stringify(m.s.inventory),before);assert.ok(m.add('water',24));assert.equal(m.weight,16);assert.equal(m.remove('bottle',50),false);assert.equal(m.count('bottle'),40);assert.equal(m.add('water',-1),false)});
test('purchases cannot charge money when inventory is full',()=>{let m=new GameModel(newGame(true));m.add('bottle',200);const before=m.s.money;assert.equal(m.buy('sandwich'),false);assert.equal(m.s.money,before);assert.equal(m.buy('unknown'),false)});
test('drinking produces exactly one refundable empty bottle',()=>{let m=new GameModel();m.add('water');m.s.needs.thirst=20;m.use(0);assert.equal(m.s.needs.thirst,65);assert.equal(m.count('water'),0);assert.equal(m.count('bottle'),1);assert.equal(m.s.stats.consumed,1)});
test('jobs reject overlap, cancellation removes parcels, finishing pays once',()=>{let m=new GameModel();assert.ok(m.startJob('courier'));assert.equal(m.count('parcel'),1);assert.equal(m.startJob('cleaning'),false);m.cancelJob();assert.equal(m.count('parcel'),0);assert.ok(m.startJob('warehouse'));completeJob(m);assert.equal(m.s.money,6500);completeJob(m);assert.equal(m.s.money,6500);assert.equal(m.s.stats.jobs,1)});
test('late delivery receives reduced payment, trained worker receives bonus',()=>{let m=new GameModel();m.s.skills.logistics=100;m.startJob('courier');m.advance(370);completeJob(m);assert.equal(m.s.money,2640)});
test('sleep crosses midnight, settles rent once, and preserves health bounds',()=>{let s=newGame(true),m=new GameModel(s);m.rent('room');s.day=s.rentDue-1;s.minute=1320;s.inside=true;s.interior='home';s.position={x:298.15,z:-2.5};let before=s.money;assert.ok(m.beginLifeAction('sleep',8));m.tickLifeAction(10);assert.equal(s.day,s.rentDue-3);assert.equal(s.minute,360);assert.equal(s.money,before-1200);assert.ok(s.needs.energy<=100);assert.equal(s.stats.slept,1);assert.ok(s.needs.health<=100)});
test('an unopened cafe earns no phantom revenue and only charges daily overhead',()=>{let m=new GameModel(newGame(true));m.acquire('cafe');m.manage('cafe','hire');let b=m.s.businesses.cafe;let before=m.s.money;m.s.minute=1439;m.advance(1);assert.equal(b.stock,3);assert.equal(b.sales,0);assert.equal(b.costs,2450);assert.equal(m.s.money,before+b.profit);m.manage('cafe','open');before=m.s.money;m.advance(1440,true);assert.equal(b.stock,3);assert.equal(b.sales,0);assert.equal(b.costs,2450);assert.equal(m.s.money,before-2450)});
test('business insolvency becomes debt and interest, cash never goes negative',()=>{let m=new GameModel(newGame(true));m.acquire('cafe');m.s.money=0;m.s.businesses.cafe.stock=0;m.advance(1440,true);assert.equal(m.s.money,0);assert.ok(m.s.debt>=2450)});
test('business acquisition cannot duplicate ownership, stock capped at seven days',()=>{let m=new GameModel(newGame(true));m.acquire('cafe');let before=m.s.money;m.acquire('cafe');assert.equal(m.s.money,before);m.manage('cafe','stock');m.manage('cafe','stock');assert.equal(m.s.businesses.cafe.stock,7);before=m.s.money;m.manage('cafe','stock');assert.equal(m.s.money,before)});
test('bank transfers preserve wealth; loan limit and repayment respected',()=>{let m=new GameModel(newGame(true));let w=m.wealth;m.bank('deposit',2000);m.bank('withdraw',1000);assert.equal(m.wealth,w);m.bank('loan',50000);assert.equal(m.wealth,w);assert.equal(m.s.debt,50000);m.bank('loan',60000);assert.equal(m.s.debt,50000);m.bank('repay',10000);assert.equal(m.s.debt,40000);assert.equal(m.wealth,w);let money=m.s.money;m.bank('withdraw',2000);assert.equal(m.s.money,money)});
test('save roundtrip includes active job, drops, interior, relationships and companies',()=>{let m=new GameModel(newGame(true));m.acquire('cafe');m.rent('room');m.s.inside=true;m.s.interior='home';m.s.position={x:300,z:3};m.startJob('courier');m.add('coffee');m.talk('mara','gift');m.add('bottle',2);m.drop(m.s.inventory.findIndex(v=>v.id==='bottle'));let parsed=validateSave(JSON.parse(JSON.stringify(m.s)));assert.deepEqual(parsed,m.s)});
test('malformed imports rejected without corrupting live state',()=>{let s=newGame();for(let edit of [v=>v.version=99,v=>v.mode='invalid',v=>v.money=-1,v=>v.day=1.5,v=>v.properties=.5,v=>v.rentDue=2.5,v=>v.needs.thirst=NaN,v=>v.inventory=[{id:'unknown',count:1}],v=>v.inventory=[{id:'bottle',count:21}],v=>v.job={type:'courier',target:'unknown',progress:0,started:0},v=>v.businesses={evil:{}},v=>v.position.x=Infinity,v=>v.skills.tech=-1]){let bad=structuredClone(s);edit(bad);assert.throws(()=>validateSave(bad))}assert.deepEqual(s,newGame())});
test('business and dropped-item validation rejects impossible imported state',()=>{let s=newGame(true);s.businesses.cafe={stock:1.5,staff:0,price:1,quality:1,marketing:false,open:true,profit:0,sales:0,costs:0};assert.throws(()=>validateSave(s));s=newGame();s.drops=[{id:'medicine',count:4,x:0,z:0}];assert.throws(()=>validateSave(s));s=newGame();s.drops=[{id:'parcel',count:1,x:0,z:0}];assert.throws(()=>validateSave(s));});
test('one contact interaction per day and a single relationship reward',()=>{let m=new GameModel();m.talk('mara','chat');m.talk('mara','chat');assert.equal(m.s.relations.mara.value,10);m.s.day++;m.talk('mara','chat');m.s.day++;m.talk('mara','chat');assert.equal(m.s.money,4000);m.s.day++;m.talk('mara','chat');assert.equal(m.s.money,4000)});
test('all eleven story chapters can be completed through real system actions',()=>{
 let m=new GameModel();for(let i=0;i<5;i++)m.collect(i);m.recycle();m.buy('water');m.use(m.s.inventory.findIndex(v=>v.id==='water'));m.startJob('courier');completeJob(m);m.s.position={...LOCATIONS.find(l=>l.id==='shelter')};assert.ok(m.beginLifeAction('shelterSleep'));m.tickLifeAction(10);assert.equal(m.s.quest,5);m.rent('room');assert.equal(m.s.quest,6);m.course('logistics');assert.equal(m.s.quest,7);
 // Earn the remainder through jobs without introducing test money.
 function earnTo(amount){let guard=0;while(m.s.money<amount){m.s.needs.energy=100;assert.ok(m.startJob('warehouse'));completeJob(m);assert.ok(++guard<200)}}
 earnTo(BUSINESSES.cafe.cost);m.acquire('cafe');assert.equal(m.s.quest,8);m.manage('cafe','hire');assert.equal(m.s.quest,9);earnTo(150000);m.property();assert.equal(m.s.quest,10);earnTo(900000);m.checkQuests();assert.equal(m.s.quest,QUESTS.length);assert.ok(m.wealth>=1000000);assert.doesNotThrow(()=>validateSave(JSON.parse(JSON.stringify(m.s))))
});

test('vehicle ownership, service, sale, and courier van pay remain consistent',()=>{const m=new GameModel(newGame(true));m.s.position={x:76,z:12};assert.ok(m.buyVehicle('van'));const van=m.s.vehicle;assert.equal(m.s.money,1820000);assert.ok(m.buyVehicle('bike'));assert.equal(m.s.fleet.length,2);m.s.vehicle=van;const before=m.s.money;m.startJob('courier');m.s.job.vehicleUsed=true;completeJob(m);assert.equal(m.s.money,before+4000);m.s.position={x:76,z:12};van.fuel=70;assert.ok(m.serviceVehicle('fuel'));assert.equal(van.fuel,100);assert.equal(m.s.money,before+3100);van.condition=50;m.s.riding=true;assert.equal(m.serviceVehicle('sell'),false);m.s.riding=false;const sale=m.s.money;assert.ok(m.serviceVehicle('sell'));assert.equal(m.s.money,sale+58500);assert.equal(m.s.fleet.length,1);assert.equal(m.s.vehicle,null);assert.doesNotThrow(()=>validateSave(m.s));});
test('invalid driving states and prototype-named items are rejected',()=>{let s=newGame();s.riding=true;assert.throws(()=>validateSave(s));s=newGame();s.inventory=[{id:'__proto__',count:1}];assert.throws(()=>validateSave(s));s=newGame();s.angle=null;assert.throws(()=>validateSave(s));s=newGame();s.job={type:'warehouse',progress:4,started:10};assert.throws(()=>validateSave(s));let m=new GameModel();assert.equal(m.startJob('arbitrary'),false);assert.equal(m.add('__proto__'),false)});
