import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from '../dist/vendor/three.module.js';import {CameraRig} from '../dist/spatial.js';import {TuningScene} from '../dist/tuning-scene.js';import {TUNING_FIXTURES} from '../dist/tuning-layout.js';import {ALLOY_STYLES,alloyGeometry,rimProfiles,createAlloyRim} from '../dist/tuning-rims.js';import {normalizeCustomization,tuningQuote,TUNING_DEFAULTS} from '../dist/tuning.js';
const world={scene:new THREE.Scene(),colliders:[],overheadColliders:[],batchStaticGroup(){}};
const boxGeo=new THREE.BoxGeometry();const kit={mat:c=>new THREE.MeshStandardMaterial({color:c}),box(parent,x,y,z,w,h,d,c,m){const mesh=new THREE.Mesh(boxGeo,m||new THREE.MeshStandardMaterial({color:c}));mesh.position.set(x,y,z);mesh.scale.set(w,h,d);parent.add(mesh);return mesh;},cylinder(){},sign(){}};
const workshop=new TuningScene(world,kit),colliders=[...world.colliders,...world.overheadColliders];
const intersects=p=>colliders.some(c=>p.x>c.x-c.w-.19&&p.x<c.x+c.w+.19&&p.z>c.z-c.d-.19&&p.z<c.z+c.d+.19&&p.y>(c.minY??-1)&&p.y<c.h+.15);
test('roof camera slab has a real lower bound; gameplay colliders unchanged',()=>{assert.deepEqual(world.colliders,TUNING_FIXTURES);assert.equal(world.overheadColliders[0].minY,4.45);});
test('approach, bay orbit and departure stay outside car/van/sport and restore exterior distance',()=>{for(const id of ['car','van','sport']){const rig=new CameraRig();let previous=null,maxStep=0,jumpAt=0,minBoom=Infinity;for(let i=0;i<1500;i++){const x=i<500?165+i*.05:i<1000?190:190-(i-1000)*.05,angle=i<500?-Math.PI/2:i<1000?-Math.PI/2+(i-500)*Math.PI*2/500:-Math.PI/2,p={x,y:-.08,z:205};const v=rig.update(p,angle,.35,11,1/60,colliders,null,workshop.cameraShelter(p,true));minBoom=Math.min(minBoom,v.distance);assert.ok(!intersects(v.position),id+' camera intersects workshop');assert.ok(Math.hypot(v.position.x-p.x,v.position.z-p.z)>3.1,id+' camera inside vehicle');if(previous){const step=Math.hypot(v.position.x-previous.x,v.position.y-previous.y,v.position.z-previous.z);if(step>maxStep){maxStep=step;jumpAt=i;}}previous=v.position;}assert.ok(minBoom>=3.4,id+' stays third person');assert.ok(maxStep<.7,id+' camera jumped '+maxStep+' at '+jumpAt);assert.ok(rig.boom>10.5,'exterior zoom restores');}});
test('six alloy styles have different shaped, recessed geometry and shared cache',()=>{assert.equal(ALLOY_STYLES.length,6);const signatures=new Set();for(const style of ALLOY_STYLES){const geo=alloyGeometry(style,.235);assert.equal(geo,alloyGeometry(style,.235));geo.computeBoundingBox();assert.ok(geo.boundingBox.min.z<-.02);assert.ok(geo.boundingBox.max.z<=0);signatures.add(JSON.stringify(Array.from(geo.attributes.position.array)));const rim=createAlloyRim(style,.235,new THREE.MeshStandardMaterial(),new THREE.MeshStandardMaterial());assert.equal(rim.children.length,5);assert.ok(rimProfiles(style).length>=5);assert.equal(normalizeCustomization({paint:'default',rims:style,rimColor:'silver'}).rims,style);assert.equal(tuningQuote(TUNING_DEFAULTS,{paint:'default',rims:style,rimColor:'silver'}).total,25000);}assert.equal(signatures.size,6);assert.equal(workshop.displayRims.length,6);});

import {createCar} from '../dist/art.js';import {applyVehicleCustomization} from '../dist/tuning.js';import {GameModel,newGame,validateSave} from '../dist/model.js';
test('every alloy previews on each vehicle without replacing rolling wheels or doors; new IDs reload',()=>{for(const id of ['car','van','sport']){const mesh=createCar(kit,id),wheels=[...mesh.userData.wheels],door=mesh.userData.driverDoor,lights=mesh.userData.vehicleLights;for(const style of ALLOY_STYLES){const s=newGame(true),v={uid:'v1',id,x:190,z:205,angle:Math.PI/2,speed:0,fuel:100,condition:100,odometer:0,purchasePrice:0,insured:false,claimCredit:0,trunk:[],parking:null,stored:false,customization:{paint:'default',rims:style,rimColor:'silver'}};s.fleet=[v];s.vehicle=v;const loaded=validateSave(JSON.parse(JSON.stringify(new GameModel(s).s)));assert.equal(loaded.fleet[0].customization.rims,style);applyVehicleCustomization(mesh,v);assert.ok(mesh.userData.rimStyleGroups[style].every(g=>g.visible&&wheels.includes(g.parent)));assert.ok(mesh.userData.rimStyleGroups.default.every(g=>!g.visible));for(const wheel of wheels)wheel.rotation.x+=.3;mesh.updateMatrixWorld(true);assert.ok(mesh.userData.rimStyleGroups[style].every(g=>g.matrixWorld.elements.every(Number.isFinite)));assert.equal(mesh.userData.driverDoor,door);assert.equal(mesh.userData.vehicleLights,lights);assert.deepEqual(mesh.userData.wheels,wheels);}}});

test('tuning preview enters and returns through a smooth third-person pose',()=>{globalThis.innerWidth=1280;globalThis.innerHeight=720;try{const normal={anchor:{x:186,y:1.3,z:210},position:{x:175,y:3.3,z:210}},w={camera:new THREE.PerspectiveCamera(),cameraRig:new CameraRig(),cameraObstacles:colliders,tuningPreview:{vehicle:{x:190,z:205}}};w.camera.position.set(175,3.3,210);let previous=w.camera.position.clone(),max=0;for(let i=0;i<360;i++){if(i===120)w.tuningPreview.frontView=true;if(i===240)w.tuningPreview=null;workshop.frameCamera(w,1/60,normal);max=Math.max(max,w.camera.position.distanceTo(previous));assert.ok(!intersects(w.camera.position),'preview clips workshop');assert.ok(w.camera.position.distanceTo(new THREE.Vector3(190,1,205))>3.4);previous.copy(w.camera.position);}assert.ok(max<1.8,'preview position snaps');assert.ok(w.camera.position.distanceTo(new THREE.Vector3(175,3.3,210))<.03);}finally{delete globalThis.innerWidth;delete globalThis.innerHeight;}});

test('entering or driving after preview immediately returns control to the normal camera rig',()=>{globalThis.innerWidth=1280;globalThis.innerHeight=720;try{const normal={anchor:{x:186,y:1.3,z:210},position:{x:175,y:3.3,z:210}},w={camera:new THREE.PerspectiveCamera(),cameraRig:new CameraRig(),cameraObstacles:colliders,model:{s:{riding:false}},transition:null,tuningPreview:{vehicle:{x:190,z:205}}};w.camera.position.set(175,3.3,210);for(let i=0;i<90;i++)workshop.frameCamera(w,1/60,normal);w.tuningPreview=null;workshop.frameCamera(w,1/60,normal);assert.ok(workshop.previewSession,'stationary close keeps the smooth return');const driving={anchor:{x:188,y:1.3,z:205},position:{x:177,y:3.3,z:205}};w.camera.position.set(driving.position.x,driving.position.y,driving.position.z);w.model.s.riding=true;workshop.frameCamera(w,1/60,driving);assert.equal(workshop.previewSession,null);assert.deepEqual(w.camera.position.toArray(),[177,3.3,205]);
 w.tuningPreview={vehicle:{x:190,z:205}};w.model.s.riding=false;for(let i=0;i<20;i++)workshop.frameCamera(w,1/60,normal);w.tuningPreview=null;w.transition={};w.camera.position.set(175,3.3,210);workshop.frameCamera(w,1/60,normal);assert.equal(workshop.previewSession,null);assert.deepEqual(w.camera.position.toArray(),[175,3.3,210]);}finally{delete globalThis.innerWidth;delete globalThis.innerHeight;}});
