import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from '../dist/vendor/three.module.js';
import {UPGRADE_DEFAULTS,normalizeUpgrades,vehiclePerformance,upgradeQuote,upgradePrice,applyUpgradeVisuals} from '../dist/vehicle-upgrades.js';
import {stepVehicle} from '../dist/movement.js';import {VEHICLES} from '../dist/data.js';import {GameModel,newGame,validateSave} from '../dist/model.js';
import {startTuningPreview,cancelTuningPreview,purchaseTuning,workshopQuote,TUNING_DEFAULTS,applyVehicleCustomization} from '../dist/tuning.js';
import {createCar} from '../dist/art.js';import {updateVehicleDamage} from '../dist/vehicle-damage.js';import {tuningPanel} from '../dist/tuning-ui.js';
const car=(id='car',uid='v1')=>({id,uid,x:190,z:205,angle:Math.PI/2,speed:0,condition:100,fuel:100,odometer:0,purchasePrice:0,insured:false,claimCredit:0,trunk:[],stored:false,parking:null,customization:{...TUNING_DEFAULTS}});
const drive=(v,input,seconds)=>{let n={...v};for(let i=0;i<Math.round(seconds*60);i++)n={...n,...stepVehicle(n,input,1/60,()=>true,VEHICLES[n.id].speed)};return n;};
const setup=()=>{const s=newGame(true);s.position={x:186,z:210};s.fleet=[car(),{...car('sport','v2'),x:178,z:202}];s.vehicle=s.fleet[0];return new GameModel(s);};
test('stock physics stay identical; engine, gearing, brakes and suspension have measured independent effects',()=>{
 for(const id of ['car','van','sport']){const v=car(id),stock=drive(v,{forward:true},1),engine=drive({...v,upgrades:{...UPGRADE_DEFAULTS,engine:'stage2'}},{forward:true},1),gear=drive({...v,upgrades:{...UPGRADE_DEFAULTS,gearbox:'stage3'}},{forward:true},1);assert.ok(Math.abs(stock.speed-5)<1e-8);assert.ok(engine.speed>stock.speed*1.17);assert.ok(gear.speed>stock.speed*1.12);
 const fast=drive({...v,upgrades:{...UPGRADE_DEFAULTS,engine:'stage3'}},{forward:true},20);assert.ok(Math.abs(fast.speed-VEHICLES[id].speed*1.07)<.001);assert.ok(fast.speed<35);
 const braking=drive({...v,speed:15},{brake:true},.5),better=drive({...v,speed:15,upgrades:{...UPGRADE_DEFAULTS,brakes:'stage3'}},{brake:true},.5);assert.ok(better.speed<braking.speed);assert.ok(better.distance<braking.distance);
 const turn=drive({...v,speed:10},{left:true},.5),precise=drive({...v,speed:10,upgrades:{...UPGRADE_DEFAULTS,suspension:'stage3'}},{left:true},.5);assert.ok(precise.angle>turn.angle);
 }const bike=car('bike');assert.deepEqual(vehiclePerformance({...bike,upgrades:{...UPGRADE_DEFAULTS,engine:'stage3'}}),vehiclePerformance(bike));
});
test('tires have distinct traction, braking and handling; combined stages remain bounded',()=>{
 const options=['stock','touring','sport','grip'].map(tires=>vehiclePerformance({...car(),upgrades:{...UPGRADE_DEFAULTS,tires}}));assert.equal(new Set(options.map(p=>JSON.stringify(p))).size,4);assert.ok(options[2].acceleration>options[3].acceleration);assert.ok(options[3].braking>options[2].braking);assert.ok(options[1].handling<1);
 const max=vehiclePerformance({...car(),upgrades:{engine:'stage3',gearbox:'stage3',brakes:'stage3',suspension:'stage3',tires:'sport',exhaust:'sport'}});assert.ok(max.acceleration<=1.55&&max.top<=1.1&&max.handling<=1.35&&max.braking<=1.65);
});
const geometry=new THREE.BoxGeometry(),kit={mat:c=>new THREE.MeshStandardMaterial({color:c}),sign(){},box(g,x,y,z,w,h,d,c,m){const o=new THREE.Mesh(geometry,m||new THREE.MeshStandardMaterial({color:c}));o.position.set(x,y,z);o.scale.set(w,h,d);g.add(o);return o;}};
test('live exhaust and spoiler preview cancel cleanly and preserve paint, damage, wheels, doors and lamps',()=>{
 for(const id of ['car','van','sport']){const v=car(id),mesh=createCar(kit,id),session=startTuningPreview(mesh,v),wheels=mesh.userData.wheels,door=mesh.userData.driverDoor,lights=mesh.userData.vehicleLights;
 session.upgrades.exhaust='dual';session.upgrades.engine='stage2';session.draft.spoiler='touring';session.draft.paint='blue';session.draft.rims='split';applyUpgradeVisuals(mesh,v,session.upgrades);applyVehicleCustomization(mesh,v,session.draft);assert.ok(mesh.userData.exhaustGroups.dual.visible&&mesh.userData.spoilerGroups.touring.visible);assert.equal(vehiclePerformance(v).acceleration,1);assert.equal(v.upgrades,undefined);
 v.condition=10;updateVehicleDamage(mesh,v,.1);const damage=mesh.userData.vehicleDamage;cancelTuningPreview(session);assert.ok(mesh.userData.exhaustGroups.stock.visible&&!mesh.userData.exhaustGroups.dual.visible&&mesh.userData.spoilerGroups.none.visible);assert.equal(damage.stage,4);assert.equal(mesh.userData.wheels,wheels);assert.equal(mesh.userData.driverDoor,door);assert.equal(mesh.userData.vehicleLights,lights);door.rotation.y=-.8;wheels.forEach(w=>w.rotation.x+=.3);mesh.updateMatrixWorld(true);assert.ok(mesh.matrixWorld.elements.every(Number.isFinite));
 }
});
test('purchase is atomic, prices scale by vehicle, repeat purchase is free of charges and cancel costs nothing',()=>{
 const m=setup(),v=m.s.fleet[0],u={...v.upgrades,engine:'stage2',brakes:'stage1',exhaust:'dual'};assert.equal(upgradePrice(v,'engine','stage2'),125000);assert.equal(upgradePrice(car('sport'),'engine','stage2'),325000);assert.equal(upgradePrice(car('van'),'engine','stage2'),168750);const quote=workshopQuote(v,v.customization,u);assert.equal(quote.total,183000);
 const original=JSON.stringify(v);m.s.money=quote.total-1;assert.equal(purchaseTuning(m,v.uid,v.customization,u),false);assert.equal(JSON.stringify(v),original);m.s.money=quote.total;assert.equal(purchaseTuning(m,v.uid,v.customization,{...u,engine:'invalid'}),false);assert.equal(m.s.money,quote.total);assert.equal(purchaseTuning(m,v.uid,v.customization,u),true);assert.equal(m.s.money,0);assert.deepEqual(v.upgrades,u);assert.equal(purchaseTuning(m,v.uid,v.customization,u),false);assert.deepEqual(m.s.fleet[1].upgrades,UPGRADE_DEFAULTS);assert.equal(upgradeQuote(car('bike'),u),null);
});
test('old saves migrate and purchased upgrades reload independently at tuned driving speeds',()=>{
 const m=setup(),v=m.s.vehicle;assert.deepEqual(v.upgrades,UPGRADE_DEFAULTS);assert.notEqual(v.upgrades,m.s.fleet[1].upgrades);v.upgrades.engine='stage3';v.speed=18;const restored=validateSave(JSON.parse(JSON.stringify(m.s)));assert.equal(restored.vehicle.upgrades.engine,'stage3');assert.equal(restored.fleet[1].upgrades.engine,'stock');assert.equal(normalizeUpgrades({engine:'broken'}).engine,'stock');
});
test('workshop has four sections, installed level, effects, price and changing preview bars',()=>{const m=setup(),v=m.s.vehicle,session=startTuningPreview(createCar(kit),v),button=(label,a,arg)=>'<button data-action="'+a+'" data-arg="'+arg+'">'+label+'</button>';const before=tuningPanel(m.s,session,button);for(const label of ['LEISTUNG','FAHRWERK','REIFEN','OPTIK','Beschleunigung','Höchstgeschwindigkeit','Bremsen','Handling','Eingebaut: Serie'])assert.ok(before.includes(label));session.upgrades.engine='stage2';const after=tuningPanel(m.s,session,button);assert.ok(after.includes('100 → 118 %'));assert.ok(after.includes('1.250'));assert.notEqual(before,after);});
