import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from '../dist/vendor/three.module.js';
import {createCar} from '../dist/art.js';import {damageStage,updateVehicleDamage,impactVehicleDamage} from '../dist/vehicle-damage.js';
import {applyVehicleCustomization} from '../dist/tuning.js';
const geo=new THREE.BoxGeometry(),materials=new Map(),mat=c=>{if(!materials.has(c))materials.set(c,new THREE.MeshStandardMaterial({color:c}));return materials.get(c);};
const kit={mat,sign(){},box(g,x,y,z,w,h,d,c,m){const b=new THREE.Mesh(geo,m||mat(c));b.position.set(x,y,z);b.scale.set(w,h,d);g.add(b);return b;}};
test('thresholds follow the existing condition without allocating effects for clean cars or bikes',()=>{assert.deepEqual([100,80,79,60,59,35,34,16,15,6,5,0].map(damageStage),[0,0,1,1,2,2,3,3,4,4,5,5]);for(const id of ['car','bike']){const m=new THREE.Group();updateVehicleDamage(m,{id,condition:100},1);assert.equal(m.userData.vehicleDamage,undefined);}});
test('progressive overlays preserve customization, rig, geometry and repair completely on all three bodies',()=>{
 for(const id of ['car','van','sport']){const m=createCar(kit,id),v={id,uid:'owned-21',condition:100,customization:{paint:'black',rims:'concave',rimColor:'silver'}},door=m.userData.driverDoor,wheels=m.userData.wheels,lights=m.userData.vehicleLights,paint=m.userData.paintMaterial;
 const original=new Map();m.traverse(o=>{if(o.geometry)original.set(o,o.geometry);});let count=0;
 for(const condition of [100,70,50,25,10,3]){v.condition=condition;applyVehicleCustomization(m,v);updateVehicleDamage(m,v,.016);const d=m.userData.vehicleDamage;if(!d)continue;const next=d.parts.filter(p=>p.mesh.visible).length;assert.ok(next>=count);count=next;assert.equal(d.particles.length,10);assert.equal(m.userData.driverDoor,door);assert.equal(m.userData.wheels,wheels);assert.equal(m.userData.vehicleLights,lights);assert.equal(m.userData.paintMaterial,paint);for(const [o,g] of original)assert.equal(o.geometry,g);}
 const d=m.userData.vehicleDamage,particles=[...d.particles];door.rotation.y=-.8;assert.ok(d.parts.some(p=>p.mesh.parent===door));wheels.forEach(w=>w.rotation.x+=1);updateVehicleDamage(m,v,.1);assert.ok(d.particles.some(p=>p.visible));updateVehicleDamage(m,v,.1,false);assert.ok(d.particles.every(p=>!p.visible));v.condition=100;updateVehicleDamage(m,v,.1);assert.ok(d.parts.every(p=>!p.mesh.visible));assert.ok(d.particles.every(p=>!p.visible));assert.deepEqual(d.particles,particles);
 }
});
test('UID placement is stable after JSON reload and differs across vehicles',()=>{const build=uid=>{const m=createCar(kit,'car'),v=JSON.parse(JSON.stringify({id:'car',uid,condition:10}));updateVehicleDamage(m,v,.1);return m.userData.vehicleDamage.parts.map(p=>p.mesh.position.toArray());};assert.deepEqual(build('v1'),build('v1'));assert.notDeepEqual(build('v1'),build('v2'));});
test('only strong impacts emit a short pooled puff; repair and distance clear it',()=>{const m=createCar(kit),v={id:'car',uid:'v3',condition:90};impactVehicleDamage(m,2,v);assert.equal(m.userData.vehicleDamage,undefined);impactVehicleDamage(m,8,v);updateVehicleDamage(m,v,.01);assert.ok(m.userData.vehicleDamage.particles.some(p=>p.visible));for(let i=0;i<50;i++)updateVehicleDamage(m,v,.02);assert.ok(m.userData.vehicleDamage.particles.every(p=>!p.visible));v.condition=10;updateVehicleDamage(m,v,.1);v.condition=100;updateVehicleDamage(m,v,.1);assert.ok(m.userData.vehicleDamage.particles.every(p=>!p.visible));});
